server:
  applicationConnectors:
    - type: http
      bindHost: 0.0.0.0
      port: 10080
  adminConnectors:
    - type: http
      bindHost: 0.0.0.0
      port: 10081

bigtable:
  projectId: flatline-dev
  instanceId: storage
  contactsTableId: contacts
  contactManifestsTableId: contact-manifests
  groupsTableId: groups
  groupLogsTableId: group-logs

authentication:
  key: c597c0cc3169b84b4420d206bfdb14e2

zkConfig:
  serverSecret: AC20oku5oMzH2tuRSkoQRtQ+dDIiRAS6nMcS/nej5aEPxSedc/8xYRWqhOzEs7xudVkPbAsFhz4UjpfUXS6frAZkJTGWCRTXPLFMexw/fkwfwvbj/k+/8ixeC1CY0iEJCUXw4tk2gfTfwrIYdSxLVJ1o+1x9rfaJJo8pJAhCMcgE8/jaUYe7VUT4ZlbzfKnWsnObXY6hLCZraMGPaRmshwgZVbDUybB+XTBtqBOsTHnCvU0GZxEH3CmwTfwbwNdIAaHXczCYHWFrCVr5nh3NXeN56yg4IPAz4SF1wT6gxegF8kgd4usTkIL+eQ5J+6VZhhtKCX8OVG+v/pVZsHjvJwYGvEBdXxrPLioJfKeGKAcqYrbt2ihbIF25PpsnABgHCFiSjE8ZN1YWOGvV9m5VZG61NBtatqE1k2Juwf/BPd0Y7lIBsR5hPD5E/NirE/KQ0Eb3D5UkV6hXeKKV3i5ruQ+McyrUBDEV98Y1rZvtP8qiFAwR0Jn/ZhwFVCVDcL13CB/ks6V5wQRcCp+lyBCfJ7RhUPXX4i1IkFTmxjcJsDACBo2p6GT5g1RTK6x2RfZZgZTSLe/odvFWtHhajCW97zsCUnXstZ8EQ6oArxFi72cs8tq5XynhsbtLN7TaUBlICHwH2NYJYZxuy6/9e/5QDp4B/D0Z64aw8gf/6xKiQqALHnyCvWXoDD5E+KW1LUFAybc0HWaDsX571519wZmRIA4FIQX0dLS/IPCvPHDhG6eI6lryvnstSPSitOdoD9glD4jF9J5B36qrFUEOlU6X8EDSaskGL/UZi4mVS8suXIUEcdCcy8wHWWhAVeuqE9/EcaNdZTFoX/N44BZ1751e1A4WhH8wP6YJbD+1Xc3z1Tp5gyj7/5lubQ5rYsYpLxBpHai0xcwAyr7P7H1bChkzkut01VQ8EtmWWj+0OgFSogwhMx4OUZibjmCd6tzJRUIiFrxf2N1N2N5gLEDYPduWGw92AXPJSugSVUA+WUo1JMfGrQODIcOkJ45KVgxbOKEJHlOiVn3boj8nPSTT6ufBYLcRYDeRyjdCW4xvrbqen1EBE9+wfNO0tCrxgdGUYLiRnIN05FYSPrrnQXbQorJDDA5I2nNbNTuZfaFeYiPiG/8CRNC8l4+gJ5tKzOD1u5LkCNHkVuW34WpSm7kNhLT0L6aD+ju4q43trGu/JkGWGNoKSlHGhhhZwtVZVQJL9z9e0G9fztKnTcQdJQkG6+2A7wuxeW6hHm1JJb2Sr101CVOi3wCLZ/wq5SfaTiZYcexPADZ+FtFMIBuyMlh1eVG2nglkrgxYYp+13RhsuSAUipgIZ3UBVt89qIk8vDVBQl7VNEi8Fcs+Qy1coWl1Z1jO7AA6sJ+hXA06lS/IntUB7k7icXVAfXkDnMj/GGG9P5dhCLSoBWQdBpfug6bcDvAlnTsdC9noP19HTkUu5uQPVwQzNrPnjC11olUYhTCx/vpkpuLZVNmSl6L5beybxydPSCMm3+OQSpExmLfUG9ZkmdlYQ2TrJ7Nuq4Lz3eCDbzNvDtFi1kOfemkLo2SaobFlDi2JECwv5n1znffJx5eE0rIJ4FttZnzCBM2sWAU3p1B1RPSlRuxnpkF9QyY6aMXFmVSa1Fl4QnKnWt66OgAOZtU1Bn5wNDT2AOaJiRRx0KvrARpxNx2wjxK075Wa+O636pHcshpTSindXi0ihbh1Ce8H8XPX10xkuQC60mtRkHE9XxpmxGzJ/Jgh/mfOJc7AcQXvjZua9q6rX69eU1DZ0Wq8vb2qjGsTJJ/dfWmWRjmRDj0Ma3sZ5lh7n6T4lisVjL0K52YetFCnyhW992FgwLUNxMSFEQrv6NhepbChSera2Wx/wtOvgcV3N5NjCl9s7wjeMP3yhJlD91wRDa0IOmeQ4nowwg5grXqaFybiifHABq0wkd14ivK7b/QA4Ybq9ba46E7kJxRYFyDdJp4RpP8JnLRxHzOD7G8ADuYXWE7PLJuAQVyJCUprE7vVlQY3UAVqI0o9JAfDeMUIO7PhiBZYaMuIj/yGz89jrRHmIh36NbTDwLPM13d2feh/ArTwi5vg2R9H0Q0RLtqUaXXaHcUK0H5k+rSYkQfJh5Vu7+ge7gUdFNjf4KR3DPx2SMiRqgWy2GMTrm8V8zEkqcVP1ZfahXb+iTo8xM+00blytLg+b9PktIzHQHQl/NQTiK3QCooKkiG2bc5qCGzpR2GhEjgHC3SI0R75pr4JOR/S6itCff54o/7AqE3joTTdsUkrtQKVvVWHIAxezBU0g0uxb3/t5YGOiHT5bQF8wirzdQ+vBuYt6KvXPdP7qfEK1KzsCuALaIXf5FGckFPGaAyWZ+YCga5To6QeNHvE3dK/oFObwjr9SKF7o2qJtG98MiztfwxD7MQo7lWLvfq17a5888XJ9apHDLkjqK2z/urLy9FdCqzZIk/H91YYFbl3rufg47g0rxPhW6bnZ8ghOz6VOiUOKt1ZRASwCvyEVjx0ATzwoSHexnwfFx5U9IV8JymQj21yRf0e3UQY6fWcOtWvftx7Z3wU7kIdWM8ykYYBtu4caFZsvOM5MWpPCy8xVzYYf9y27qljouvrurRWLhozaIwBXkF36hH8z5XBjjYYlKHZcKkrlxb+kugZoQzE/jHZ1wcUGdIDcESyQtfS9AVJnn+eP3qZcOIA7pXk2nn8XSWUQALqGWdtNJC7GR6VMWmQb9sUMEK/pDpb8dBsRJbQSwYFi/pergtZR/DkoAxeU1UHE7ohhJ1O92kIKhLMPp9smwEiWgcw2yko7d/6U8tRZTtV++ZOBE5qoZoAgpGGA2VRDW5YZTJN6z215ibcmVmATSZ3KiYq8dKgQV8P3XpIfGIJg7zE9IC3RV9niHGopBw2gdiPEsZnCnOMkA+mqRJf9gh2NQ0korj5EL70l9pNkngPO9BOKmKs5liomdPfCFGjAvIG+wiUeoxGqEjyK6HW9pze/HR3QiRSuCJjcXa/Lz0ANLk3CL13KoE25IqRvTTKbE248H3faG/shkrykzpI4T82pauZzAwebxhqHwhMC55o2T4GWEFAIeU8A8b5EHYYKOEG6Hp2GrNq+qAKGOY9sCxv79Fd5CkQTkiieJlJ74EIt5XiCJ15R+to6MpjdOC4hngJqbm6h6QteQA4Mpr49QcazGz52tZmjK73K4iYYDLOSkNAciH6PSVYT3yezHrrHkVucSKnxaLIhPfNq3sI0t8Szb2pSSpT5IYj7hFv/X8EDAfh+GAgFRe6P8EQdw5HrB674meDRYjWhU5OlWXvkglrVEJkSwfXhl7sOv1qQV8kfqrKnZ8n34Dy5k7FgT1HCemsD8ApTNm+byhuzhgnZS+me1cGftAxvTR0DY9/9jAKU8kKnxxcgoHb//PV3an2Hxw3O2oi7pA+Ip2K3hNLAwiC+KpOldKaZhPs5uTC5JJFwweEXu2+EqtLixfjShkpC9P8klMzSe4uvPBr9n3uui7u2sWlStHn3AhFj3RZGzoDpR3uSH8dzhFBIxf1+m9BpVjOBPbHRv/m6evCT4tC/Q/SUo1q2T4AIJUGjoIg9XNQV+L6SLX+k8x78AREpK0PATAMhLWRMNTVF4dN0rYmTw1fBgckXFAz7n25Q0iTx5IP

cdn:
  accessKey: test
  accessSecret: test
  bucket: CDN
  region: us-east-1

datadog:
  apiKey: test
  step: PT10S
  environment: test
  batchSize: 5000

group:
  maxGroupSize: 1001
  maxGroupTitleLengthBytes: 1024
  maxGroupDescriptionLengthBytes: 8192
  externalServiceSecret: 3f9b8e5f981f7d5b31d86e0ba883837fdd65e6ea375a698a28fa1f1e468a9a21
