name: Sync Upstream
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: write
  # Required to sync changes to workflows.
  actions: write
jobs:
  sync:
    name: Sync
    if: "github.repository_owner == 'mollyim'"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: upstream
          fetch-depth: 0
          token: ${{ secrets.PUBLISH_PAT || secrets.GITHUB_TOKEN }}
      - name: Fetch & Merge
        run: |
          git remote add upstream https://github.com/signalapp/storage-service.git
          git fetch upstream
          git merge --ff-only upstream/main
      - name: Push Changes
        run: |
          git push origin upstream
          git tag | grep -xP 'v\d+(?:\.\d+){2,3}' | xargs -r git push origin
